# Railway.toml

# Build configuration
[build]
# Name of the build step
name = "Rust Build"
# Command to build the Rust application
command = "cargo build --release"

# Start configuration
[start]
# Name of the run step
name = "Rust Run"
# Command to run the Rust application
command = "cargo run"